In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:\\Users\\meerh\\OneDrive\\Documentos\\Projetos\\esp32-fall-detection\\data\\raw\\acc_gyr.csv')
df.head()

   xAcc  yAcc  zAcc  xGyro  yGyro  zGyro label
0  6.99 -0.57 -7.28  -2.75  -3.23   2.62  fall
1  6.51 -0.75 -6.93  -0.67  -6.35   4.64  fall
2  6.22 -0.63 -6.73   0.79  -5.49   3.85  fall
3  6.34 -0.62 -6.80   1.59  -2.26   0.67  fall
4  6.49 -0.39 -6.60   0.67  -0.24  -1.10  fall

In [3]:
df['label'].value_counts()

label
light    27600
walk     19200
fall     18401
sit      16000
step      6000
rfall     5599
lfall     4000
Name: count, dtype: int64

In [13]:
df['label'] = df['label'].replace('light', 'normal')
df['label'] = df['label'].replace('walk', 'normal')
df['label'] = df['label'].replace('sit', 'normal')
df['label'] = df['label'].replace('step', 'normal')
df['label'] = df['label'].replace('rfall', 'fall')
df['label'] = df['label'].replace('lfall', 'fall')

In [14]:
df['label'].value_counts()

label
normal    68800
fall      28000
Name: count, dtype: int64

In [15]:
df.describe()

,xAcc,yAcc,zAcc,xGyro,yGyro,zGyro
count,96800.000000,96800.000000,96800.000000,96800.000000,96800.000000,96800.000000
mean,7.201229,-1.341302,-3.059421,-1.226996,-0.231135,0.121116
std,3.009094,3.049660,5.368511,35.448655,25.118186,29.100135
min,-39.240000,-39.240000,-39.240000,-483.400000,-437.810000,-354.000000
25%,5.740000,-2.900000,-6.260000,-13.670000,-6.160000,-11.410000
50%,7.040000,-1.310000,-4.920000,-0.490000,0.370000,-0.920000
75%,8.390000,0.350000,-2.410000,11.780000,7.450000,12.820000
max,39.240000,39.240000,39.240000,439.390000,317.380000,304.870000

In [16]:
df.isna().sum()

xAcc     0
yAcc     0
zAcc     0
xGyro    0
yGyro    0
zGyro    0
label    0
dtype: int64

In [17]:
df.to_csv('C:\\Users\\meerh\\OneDrive\\Documentos\\Projetos\\esp32-fall-detection\\data\\processed\\acc_gyr.csv', index=False)